# Use a base image with Java runtime
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot application JAR file into the container
COPY target/superhero-0.0.1-SNAPSHOT.jar /app/superhero-0.0.1-SNAPSHOT.jar

# Expose the port that the application will run on
EXPOSE 8080

# Set the entry point to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "superhero-0.0.1-SNAPSHOT.jar"]
