services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-superhero-postgres
    image: superhero-postgres
    container_name: superhero-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: superhero_db
      POSTGRES_USER: superhero
      POSTGRES_PASSWORD: superhero
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    build:
      context: .
      dockerfile: Dockerfile-superhero-springboot
    image: superhero-springboot
    container_name: superhero-springboot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/superhero_db
      SPRING_DATASOURCE_USERNAME: superhero
      SPRING_DATASOURCE_PASSWORD: superhero

volumes:
  postgres_data:
