# Use the official PostgreSQL image from the Docker Hub
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=superhero_db
ENV POSTGRES_USER=superhero
ENV POSTGRES_PASSWORD=superhero

# Copy initialization scripts (optional)
COPY init.sql /docker-entrypoint-initdb.d/
